### ISSUE TITLE
Checkbox redesign

### ISSUE THREAD

**Issue by Roseskk** [DevBuffProject/devbuff-frontend#517]
Стилизуйте чекбокс пж

**Comment by BigTows** [comment]
Какой, где?

**Comment by Roseskk** [comment]
Skill Settings там вкладка , он не оч красивый )

**Comment by BigTows** [comment]
Вот это?)
![image](https://user-images.githubusercontent.com/9078504/121819037-b2fb3b00-cc93-11eb-8a6f-3e78934edf92.png)

**Comment by BigTows** [comment]
Это к @7architect , ну если у тебя есть идеи) Ждем pullrequest в ветку vite

**Comment by Roseskk** [comment]
Ага именно  :D

**Comment by Roseskk** [comment]
Завтра  запулю

**Comment by BigTows** [comment]
Опана

**Comment by 7architect** [comment]
Checkoxes redesigned

**Comment by BigTows** [comment]
ted
